version: "3.9"
services:
  db:
    image: postgres:17
    container_name: explore_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: explore
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  explore-service:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: explore
      GRPC_PORT: 50051
    ports:
      - "50051:50051"

volumes:
  db_data:
